public enum Pools
{
    DefaultBullet,
    DefaultBulletMuff,
    LongBullet,
    LongBulletMuff,
    RedBulletMuff,
    ShortBullet,
    BoxDestroyParticle,
    ShootSmoke,
    ShootSparks,
    HitParticle,
    ZombieHitParticle,
    ZombieDeathParticle,
    ZombieHead,
    ZombieBody,
    ZombieLeg,
    ZombieArm,
    ZombieBiteParticle
}