public enum Pools
{
    DefaultBullet,
    DefaultBulletMuff,
    LongBullet,
    LongBulletMuff,
    RedBulletMuff,
    ShortBullet,
    WoodItemDestroyParticle,
    ShootSmoke,
    ShootSparks,
    HitParticle,
    EntityHitParticle,
    EntityDeathParticle,
    ZombieHead, ZombieBody, ZombieLeg, ZombieArm, ZombieBiteParticle, 
    PlayerHead, PlayerBody, PlayerStrips, PlayerLeg, PlayerArm, 
    TVDestroyParticle,
    GreenZombieExplosion,
    FuelBarrelExplosion,
    HumanHead, HumanLeftLeg, HumanRightLeg, HumanRightArm, HumanLeftArm, 
    BlueBird, RedBird, GreenBird, YellowBird, 
    FuelBarrelSmoke, 
    Missile, 
    GreenItemDestroy, 
    HealthBonus,
    AmmoBonus, WeaponBonus,
    DefaultWeapon, Rifle, Minigun, Vintorez, MachineGun, Uzi, Shotgun
}