public enum Pools
{
    DefaultBullet,
    DefaultBulletMuff,
    LongBullet,
    LongBulletMuff,
    RedBulletMuff,
    ShortBullet,
    WoodItemDestroyParticle,
    ShootSmoke,
    ShootSparks,
    DefaultHitParticle,
    EntityHitParticle,
    EntityDeathParticle,
    ZombieHead, ZombieBody, ZombieLeg, ZombieArm, ZombieBiteParticle, 
    PlayerHead, PlayerBody, PlayerStrips, PlayerLeg, PlayerArm, 
    TVDestroyParticle,
    GreenZombieExplosion,
    FuelBarrelExplosion,
    HumanHead, HumanLeftLeg, HumanRightLeg, HumanRightArm, HumanLeftArm, 
    BlueBird, RedBird, GreenBird, YellowBird, 
    FuelBarrelSmoke, 
    Missile, 
    GreenItemDestroy, 
    HealthBonus,
    AmmoBonus,
    DefaultWeapon, Rifle, Minigun, Vintorez, MachineGun, Uzi, Shotgun,
    HealSpellParticle,
    MetalHitParticle,
    WoodenObjHitParticle,
    EntityDestroyParticle1, EntityDestroyParticle2, EntityDestroyParticle3, EntityDestroyParticle4, 
    EntityDestroyParticle5, EntityDestroyParticle6, EntityDestroyParticle7, EntityDestroyParticle8,
    EntityDestroyParticle9
}